# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

global tcl_platform

switch $tcl_platform(os) {
  "FreeBSD" {
    set script "
      load [list [file join $dir libxotcl1.6.2.so]]
    "
    package ifneeded XOTcl 1.6.2 $script
    
  }
  "Darwin" {
    set script "
      load [list [file join $dir libxotcl1.6.5.dylib]]
    "
    package ifneeded XOTcl 1.6.5 $script
  }
  "Windows NT" {
    set script "
      load [list [file join $dir xotcl163.dll]]
    "
    package ifneeded XOTcl 1.6.3 $script
  }
  "Linux" {
    set script "
      load [list [file join $dir libxotcl1.6.5.so] XOTcl]
    "
    package ifneeded XOTcl 1.6.5 $script    
  }
}